version: '3'

services:
    app:
        image: golang:latest
        ports:
            # ホスト側のポート：コンテナ側のポート
            - "8888:8888"
        container_name: go-app
        volumes:
            - ./:/go
        tty: true
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: go-mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: password
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306  
